// Generated by gencpp from file interaccion/Multiplicador.msg
// DO NOT EDIT!


#ifndef INTERACCION_MESSAGE_MULTIPLICADOR_H
#define INTERACCION_MESSAGE_MULTIPLICADOR_H

#include <ros/service_traits.h>


#include <interaccion/MultiplicadorRequest.h>
#include <interaccion/MultiplicadorResponse.h>


namespace interaccion
{

struct Multiplicador
{

typedef MultiplicadorRequest Request;
typedef MultiplicadorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Multiplicador
} // namespace interaccion


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interaccion::Multiplicador > {
  static const char* value()
  {
    return "d1d48bd1a6a0e98317f90b1d6ea7b6fa";
  }

  static const char* value(const ::interaccion::Multiplicador&) { return value(); }
};

template<>
struct DataType< ::interaccion::Multiplicador > {
  static const char* value()
  {
    return "interaccion/Multiplicador";
  }

  static const char* value(const ::interaccion::Multiplicador&) { return value(); }
};


// service_traits::MD5Sum< ::interaccion::MultiplicadorRequest> should match
// service_traits::MD5Sum< ::interaccion::Multiplicador >
template<>
struct MD5Sum< ::interaccion::MultiplicadorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interaccion::Multiplicador >::value();
  }
  static const char* value(const ::interaccion::MultiplicadorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interaccion::MultiplicadorRequest> should match
// service_traits::DataType< ::interaccion::Multiplicador >
template<>
struct DataType< ::interaccion::MultiplicadorRequest>
{
  static const char* value()
  {
    return DataType< ::interaccion::Multiplicador >::value();
  }
  static const char* value(const ::interaccion::MultiplicadorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interaccion::MultiplicadorResponse> should match
// service_traits::MD5Sum< ::interaccion::Multiplicador >
template<>
struct MD5Sum< ::interaccion::MultiplicadorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interaccion::Multiplicador >::value();
  }
  static const char* value(const ::interaccion::MultiplicadorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interaccion::MultiplicadorResponse> should match
// service_traits::DataType< ::interaccion::Multiplicador >
template<>
struct DataType< ::interaccion::MultiplicadorResponse>
{
  static const char* value()
  {
    return DataType< ::interaccion::Multiplicador >::value();
  }
  static const char* value(const ::interaccion::MultiplicadorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERACCION_MESSAGE_MULTIPLICADOR_H
