// Generated by gencpp from file interaccion/MultiplicadorRequest.msg
// DO NOT EDIT!


#ifndef INTERACCION_MESSAGE_MULTIPLICADORREQUEST_H
#define INTERACCION_MESSAGE_MULTIPLICADORREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interaccion
{
template <class ContainerAllocator>
struct MultiplicadorRequest_
{
  typedef MultiplicadorRequest_<ContainerAllocator> Type;

  MultiplicadorRequest_()
    : entrada(0)  {
    }
  MultiplicadorRequest_(const ContainerAllocator& _alloc)
    : entrada(0)  {
  (void)_alloc;
    }



   typedef int64_t _entrada_type;
  _entrada_type entrada;





  typedef boost::shared_ptr< ::interaccion::MultiplicadorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interaccion::MultiplicadorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MultiplicadorRequest_

typedef ::interaccion::MultiplicadorRequest_<std::allocator<void> > MultiplicadorRequest;

typedef boost::shared_ptr< ::interaccion::MultiplicadorRequest > MultiplicadorRequestPtr;
typedef boost::shared_ptr< ::interaccion::MultiplicadorRequest const> MultiplicadorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interaccion::MultiplicadorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interaccion::MultiplicadorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::interaccion::MultiplicadorRequest_<ContainerAllocator1> & lhs, const ::interaccion::MultiplicadorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.entrada == rhs.entrada;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::interaccion::MultiplicadorRequest_<ContainerAllocator1> & lhs, const ::interaccion::MultiplicadorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace interaccion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::interaccion::MultiplicadorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interaccion::MultiplicadorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interaccion::MultiplicadorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interaccion::MultiplicadorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interaccion::MultiplicadorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interaccion::MultiplicadorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interaccion::MultiplicadorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f84bc19c332ccbd56a70d59a2121c58f";
  }

  static const char* value(const ::interaccion::MultiplicadorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf84bc19c332ccbd5ULL;
  static const uint64_t static_value2 = 0x6a70d59a2121c58fULL;
};

template<class ContainerAllocator>
struct DataType< ::interaccion::MultiplicadorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interaccion/MultiplicadorRequest";
  }

  static const char* value(const ::interaccion::MultiplicadorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interaccion::MultiplicadorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 entrada\n"
;
  }

  static const char* value(const ::interaccion::MultiplicadorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interaccion::MultiplicadorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.entrada);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiplicadorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interaccion::MultiplicadorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interaccion::MultiplicadorRequest_<ContainerAllocator>& v)
  {
    s << indent << "entrada: ";
    Printer<int64_t>::stream(s, indent + "  ", v.entrada);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERACCION_MESSAGE_MULTIPLICADORREQUEST_H
