// Generated by gencpp from file interaccion/usuario.msg
// DO NOT EDIT!


#ifndef INTERACCION_MESSAGE_USUARIO_H
#define INTERACCION_MESSAGE_USUARIO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <interaccion/inf_personal_usuario.h>
#include <interaccion/pos_usuario.h>

namespace interaccion
{
template <class ContainerAllocator>
struct usuario_
{
  typedef usuario_<ContainerAllocator> Type;

  usuario_()
    : infPersonal()
    , emocion()
    , posicion()  {
    }
  usuario_(const ContainerAllocator& _alloc)
    : infPersonal(_alloc)
    , emocion(_alloc)
    , posicion(_alloc)  {
  (void)_alloc;
    }



   typedef  ::interaccion::inf_personal_usuario_<ContainerAllocator>  _infPersonal_type;
  _infPersonal_type infPersonal;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _emocion_type;
  _emocion_type emocion;

   typedef  ::interaccion::pos_usuario_<ContainerAllocator>  _posicion_type;
  _posicion_type posicion;





  typedef boost::shared_ptr< ::interaccion::usuario_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interaccion::usuario_<ContainerAllocator> const> ConstPtr;

}; // struct usuario_

typedef ::interaccion::usuario_<std::allocator<void> > usuario;

typedef boost::shared_ptr< ::interaccion::usuario > usuarioPtr;
typedef boost::shared_ptr< ::interaccion::usuario const> usuarioConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interaccion::usuario_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interaccion::usuario_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::interaccion::usuario_<ContainerAllocator1> & lhs, const ::interaccion::usuario_<ContainerAllocator2> & rhs)
{
  return lhs.infPersonal == rhs.infPersonal &&
    lhs.emocion == rhs.emocion &&
    lhs.posicion == rhs.posicion;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::interaccion::usuario_<ContainerAllocator1> & lhs, const ::interaccion::usuario_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace interaccion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::interaccion::usuario_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interaccion::usuario_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interaccion::usuario_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interaccion::usuario_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interaccion::usuario_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interaccion::usuario_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interaccion::usuario_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4360dec30567ba1372bc2e32a667a82";
  }

  static const char* value(const ::interaccion::usuario_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4360dec30567ba1ULL;
  static const uint64_t static_value2 = 0x372bc2e32a667a82ULL;
};

template<class ContainerAllocator>
struct DataType< ::interaccion::usuario_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interaccion/usuario";
  }

  static const char* value(const ::interaccion::usuario_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interaccion::usuario_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inf_personal_usuario infPersonal\n"
"string emocion\n"
"pos_usuario posicion\n"
"\n"
"================================================================================\n"
"MSG: interaccion/inf_personal_usuario\n"
"string nombre\n"
"int32 edad\n"
"string[] idiomas\n"
"\n"
"================================================================================\n"
"MSG: interaccion/pos_usuario\n"
"int32 x\n"
"int32 y\n"
"int32 z\n"
;
  }

  static const char* value(const ::interaccion::usuario_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interaccion::usuario_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.infPersonal);
      stream.next(m.emocion);
      stream.next(m.posicion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct usuario_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interaccion::usuario_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interaccion::usuario_<ContainerAllocator>& v)
  {
    s << indent << "infPersonal: ";
    s << std::endl;
    Printer< ::interaccion::inf_personal_usuario_<ContainerAllocator> >::stream(s, indent + "  ", v.infPersonal);
    s << indent << "emocion: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.emocion);
    s << indent << "posicion: ";
    s << std::endl;
    Printer< ::interaccion::pos_usuario_<ContainerAllocator> >::stream(s, indent + "  ", v.posicion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERACCION_MESSAGE_USUARIO_H
